// Generated by FlutterFire CLI. Run `flutterfire configure` to regenerate
// with real values from your Firebase project.
//
// Steps to configure:
//   1. Go to https://console.firebase.google.com and create a project
//   2. Enable Firestore, Auth (Anonymous), and Storage in the Firebase console
//   3. Run: dart pub global activate flutterfire_cli
//   4. Run: flutterfire configure
//   5. This file will be overwritten with real credentials

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not configured for this platform. '
          'Run flutterfire configure to set up your project.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsCm2ll2FAjGOOBIcSk3U3bN99SlHIL_c',
    appId: '1:105736039803:web:b81de3631f48b0a474a1de',
    messagingSenderId: '105736039803',
    projectId: 'first-project-e258e',
    authDomain: 'first-project-e258e.firebaseapp.com',
    storageBucket: 'first-project-e258e.firebasestorage.app',
    measurementId: 'G-JL6D442478',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVap2k1jQuFbxdDhJj5utLjFpZwjj1Z84',
    appId: '1:105736039803:android:43d1c59d52ab0a6174a1de',
    messagingSenderId: '105736039803',
    projectId: 'first-project-e258e',
    storageBucket: 'first-project-e258e.firebasestorage.app',
  );

}